### ISSUE TITLE
[ERROR]上报 Event 数据到 http://127.0.0.1:8080 失败

### ISSUE THREAD

**Issue by QiuyanLiu-64bit** [markity/qq-gpt3.5-bot#1]
**提交 issue 前，请先确认：**
我已看过 FAQ，此问题不在列表中
我已看过其他 issue，他们不能解决我的问题
**表现**
按照步骤操作后后台报错
![image](https://user-images.githubusercontent.com/99961042/228295009-be9e6868-ba8e-41f1-a9b1-6bf890669fa9.png)
![image](https://user-images.githubusercontent.com/99961042/228295055-7af15449-2b2a-43ca-8709-480e1866db6f.png)
![image](https://user-images.githubusercontent.com/99961042/228295198-4cdd986f-bbfb-482a-8dde-6bb157c66a8e.png)

**运行环境:**
操作系统：Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-58-generic x86_64)阿里云ECS
代理：V2ray
代理工具：proxychains4
**复现步骤**
go-cqhttp中：
vim config.yml
./go-cqhttp
proxychains4 ./go-cqhttp
main.go中：
   72  cd main.go
   73  vim main.go
   74  go run main.go
   75  proxychains4 go run main.go
**预期行为**
无报错
**截图**
以上
其他内容
linux新手，请多指教

**Comment by markity** [comment]
你有没有go run main.go

**Comment by markity** [comment]
cd到main.go的同级目录，go run main.go, 之后http服务会在127.0.0.1:8080跑起来，如果不行请截图执行go run main.go的结果

**Comment by QiuyanLiu-64bit** [comment]
go run main.go 截图如下：
![image](https://user-images.githubusercontent.com/99961042/228303887-2aa8ab12-4d39-46b7-bee0-97cc53a2d080.png)
![image](https://user-images.githubusercontent.com/99961042/228303909-dbff1133-925b-4db2-beba-b246faa3c851.png)
另外，main.go 只更改了api key（自己账号的）, group id；config.yml只更改了uin和password；能够通过命令proxychains4 curl www.google.com访问google

**Comment by markity** [comment]
好的，目测是防火墙的问题，将main.go 341行的r.Run()改为r.Run("127.0.0.1:8080")也许能解决问题

**Comment by markity** [comment]
如果还是不行，明天我再来解决

**Comment by markity** [comment]
顺便把config.yml的address改成127.0.0.1:5700

**Comment by QiuyanLiu-64bit** [comment]
谢谢作者，我已照做，且在阿里云ECS控制台上放行相关端口，上述报错未出现。但是群内@时并未给出回复，可能是哪方面的问题。日志如下：
![image](https://user-images.githubusercontent.com/99961042/228425378-10cab363-9e05-4c96-bc80-9f68a367e5be.png)

**Comment by markity** [comment]
不好意思，这是我的疏忽，把304行代码那串数字改成自己的qq号就行了

**Comment by markity** [comment]
3402002560是我的qq号，你改成自己自己的

**Comment by QiuyanLiu-64bit** [comment]
再次感谢作者，现在已能回复，但有个小问题：
![image](https://user-images.githubusercontent.com/99961042/228435553-b4a7b8ae-a238-4baa-82c4-1cd837e890b5.png)
网址显示：
![image](https://user-images.githubusercontent.com/99961042/228435624-6d81245a-0bf2-41d4-ab51-4255877e438d.png)
本次使用的openAI账号是Gmail账号以及Gmail账号的密码，api在playground可用，请问解决办法

**Comment by markity** [comment]
原因是没走代理，给系统上全局代理能解决问题

**Comment by markity** [comment]
你浏览器能访问那个网址是因为浏览器走了代理，但是go程序没有走代理，所以timeout

**Comment by markity** [comment]
比如开tun代理

**Comment by QiuyanLiu-64bit** [comment]
tun代理是clash那边的，linux版本的只有图形界面的教程，于是我尝试使用
export http_proxy="socks5://127.0.0.1:10808"
设置全局代理，命令：curl www.google.com能够正常返回，
但是@后仍然回复timeout，请问有其他方法使go程序走代理吗

**Comment by markity** [comment]
能否加我qq, 我改下代码发给你1494645263
